### ISSUE TITLE
Not returning anything

### ISSUE THREAD

**Issue by baguscodestudio** [BaziForYou/MugShotBase64#1]
Fresh install of the script. It does not print anything with the existing command you provided.
![image](https://user-images.githubusercontent.com/60974759/148250824-0ccdc82f-19b9-4fca-898b-e23f573baac0.png)
Is there any dependencies for the script?

**Comment by BaziForYou** [comment]
fixed thanks for reporting
[commit](https://github.com/BaziForYou/MugShotBase64/commit/798b5c175efeb6ca5db9f4afa4eede7063e2d5f1)
